<?php

namespace Dragon;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-16 at 13:18:37.
 */
class BasicResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var BasicResponse
     */
    protected $object;
    protected $output;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->output = 'this should be captured in buffer.';

        $this->code = 12435;

        $this->headers = ['header-key' => 'header-value'];

        $this->object = new BasicResponse($this->output, $this->headers,
            $this->code);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Dragon\BasicResponse::execute
     * @todo   Implement testExecute().
     */
    public function testExecuteOutput()
    {
//        ob_start();
//        
//        $this->object->execute();
//        
//        $result = ob_end_clean();
//        
//        $expect = $this->output;
//        
//        $this->assertEquals($expect, $result);
        
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
