<?php

namespace Dragon;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-16 at 12:44:41.
 */
class BasicRequestFactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var BasicRequestFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BasicRequestFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Dragon\BasicRequestFactory::createRequest
     * @todo   Implement testCreateRequest().
     */
    public function testCreateRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
